alias ll='ls -alF'
alias la='ls -A' 
alias l='ls -CF' 
alias ls='ls --color=auto' 
alias grep='grep --color=auto' 
alias cls='clear' 
alias frl='flutter run -d linux'
#alias frw='flutter run -d chrome'
alias fpg='flutter pub get'
#alias f='flutter '
alias gita='git add .'
alias gits='git status'
alias gitc='git commit -m' 
alias gitp='git push'
alias upgrade='sudo apt update && sudo apt upgrade'
alias video='mpv '
alias rr='locate reboot-required'
alias dd='dd status=progress '
alias fcr='echo \"flutter\ create\ \-\-project\-name\ Calculator\ \-\-org\ com\.vishnu\ \-\-description\ \"A\ simple\ calculator\ app\ to\ check\ my\ Flutter\ knowledge\.\ \ Calculator\/'
alias cdw='cd /home/saivishnu/Documents/cheat-sheets'
alias m='make '
alias mr='make run'
alias cdp='cd /home/saivishnu/Programs'
alias vim='nvim'
